### PR TITLE
Updated requirements.txt with pandas, editdistance, py-rouge, and verbose output from poetry

### PR DESCRIPTION
**Pull request by atreyasha**
PR to address #4. `requirements.txt` here has been printed using a virtual environment managed with `poetry`, so the output is more verbose because it prints out dependencies of packages as well. Feel free to make it less verbose if that is better. Following was the command used to generate the file:

```shell
poetry export -f requirements.txt --without-hashes -o requirements.txt
```

Also, I just used the latest versions of `pandas`, `editdistance` and `py-rouge` here. This worked for my tests, but feel free to downgrade these to match the versions used in your experiments.

### CODE REVIEW

**Comment by atreyasha** [comment]
In addition, I also added a line in `README.md` to make `multi-bleu.perl` executable before the evaluation commands, because the evaluation pipeline threw an error for that.

**Review by ashutoshml — CHANGES_REQUESTED** [review]
Hi @atreyasha,

There seem to be a lot of indirect dependencies here. Can we remove the non-essentials, so that we have minimal changes in the requirements.txt file?

**Comment by atreyasha** [comment]
Hi again,

I think it would be better if you guys edited the `requirements.txt` on your end, since you know exactly what needs to be changed and what should be kept the same. It might end up being a guessing game otherwise :shrug:

Will close this PR, the relevant information is in #4.

**Comment by ashutoshml** [comment]
Makes sense.

Thanks for helping.

**Pull request closed without merging**
